#!/usr/local/bin/python3
"""
File: analyze (3.X)
Analyzes a server log file

analyze <file> <options>

Available analyzers:

  * Combined access log: `access/combined`

The following options are available:

  --daterange       Return only logs within the given range
                    Format: '%d/%b/%Y:%H:%M:%S %z,%d/%b/%Y:%H:%M:%S %z'
                    Example: '17/Sep/2017:03:32:49 -0400,17/Sep/2017:03:32:49 -0400'

  --ip              Return only logs with certain IPs. Comma separated list.
                    Format: 'IP' or 'IP,IP'

  --url             Return only logs that match a certain request url
                    Format: regular expression

  --useragent       Return only logs that match a certain user agent
                    Format: regular expression
"""

#
# ./analyze ~/Desktop/logs/hub-ssl.access --url=baltimore-food-deserts --daterange='23/Jan/2018:08:38:45 -0500,23/Jan/2018:08:38:59 -0500'
# ./analyze files/jhu-ssl.access --daterange='01/Jul/2018:03:23:16 -0400,01/Jul/2018:03:23:30 -0400'
# ./analyze files/jhu-ssl.access --ip=23.67.53.60
# ./analyze files/shortened-access.log --useragent=Chrome
# ./analyze files/shortened-access.log --useragent=Chrome

import sys
from parsers.argument import ArgumentParser

from parsers.access.combined import Combined
LogParser = Combined

args = sys.argv[2:]
file = sys.argv[1]


# # use this when there is more than one parser
# # dynamically load the parser
# logparsers = {
#   'access/combined': {
#     'package': 'parsers.access.combined',
#     'name': 'Combined'
#   }
# }
# parser = logparsers.get(sys.argv[1])
# LogParser = getattr(__import__(parser.get('package'), fromlist=[parser.get('name')]), parser.get('name'))
#
# args = sys.argv[3:]
# file = sys.argv[2]


# parse the options
argparser = ArgumentParser(args)
options = argparser.parse()


# parse logs
parser = LogParser(open(file, 'r'), options)
results = parser.parse()

# print results
for result in results:
  print(result)
